### ISSUE TITLE
Skroutz::PaginatedCollection#each_page

### ISSUE THREAD

**Issue by Zorbash** [skroutz/skroutz.rb#31]
Allow iterating the pages of a collection with a block.

Example:
```ruby
client = Skroutz::Client.new('client_id', 'client_secret')
client.categories.each_page(per: 5) do |page|
  page.each { |category| do_something }
end
```

It's expected to work like [ActiveRecord::Batches#find_in_batches](http://api.rubyonrails.org/classes/ActiveRecord/Batches.html#method-i-find_in_batches)

**Comment by mikezaby** [comment]
`client.categories.all` should return all categories immediately, I think we want that you propose without all
`client.categories.each_page(per: 5)`

**Comment by Zorbash** [comment]
@mikezaby you're right. Updated the description.
