### ISSUE TITLE
Namespace the classes that represent resources

### ISSUE THREAD

**Issue by mikezaby** [skroutz/skroutz.rb#34]

**Comment by Zorbash** [comment]
@mikezaby Are you suggesting namespacing under a `resources` namespace?

Example `class Skroutz::Sku` to become `Skroutz::Resources::Sku`?
Care to submit a PR for this one?

**Comment by mikezaby** [comment]
Yes, excactly. I could try to make this PR.

**Comment by fotos** [comment]
@mikezaby care to provide a rationale for this change first? Why should we namespace the resources? What kind of namespace conflict did you encounter?

**Comment by mikezaby** [comment]
I think that we need the namespace for the resources, so we can have a clean and easy to understand structure, which class is for the resources and which is for the 'core' functionality.

**Comment by fotos** [comment]
@mikezaby OK agreed, it's not a bad idea after all. It will also separate the resources from the rest of the client in `lib/skroutz/`. PR is more than welcome.

**Comment by Zorbash** [comment]
Resolved by 6f7ac3bbf80c6
