### ISSUE TITLE
Skroutz::PaginatedCollection doesn't have a next (or previous) page, when it should.

### ISSUE THREAD

**Issue by gusandrianos** [skroutz/skroutz.rb#37]
This should return the first page of the category "cases" for "iphone"
`arr = @skroutz.categories(579).skus(q: 'iphone')`

To be precise, this returns a `Skroutz::PaginatedCollection` but the methods `next?` and `previous?` return `false`. Of course, if I try to `arr.next_page` I get nil.

The following also returns a `Skroutz::PaginatedCollection` but `next?` and `previous?` return true and `arr.next_page` gives me the next page as it should.
`arr = @skroutz.search('iphone').first.skus.all.first.products.page(1)`

Note that `search('iphone').first` asks for the first category of the search results, so it's not like I am asking for different things. That's why I chose the 579 category for the first case, which has endless results.

**Comment by Zorbash** [comment]
This isn't a `skroutz.rb` issue. 

If my memory serves me right, it happens because the HTTP response of 
`@skroutz.categories(579).skus(q: 'iphone')` is missing the required pagination header (see: https://github.com/skroutz/skroutz.rb/blob/master/lib/skroutz/parsing.rb#L43).

Can you setup a logger (see: https://github.com/skroutz/skroutz.rb#logger) and verify?

**Comment by GusAndrianos** [comment]
Can you explain a bit what you linked?
I will try it tomorrow. Thanks for responding.

**Comment by Zorbash** [comment]
@GusAndrianos The client depends on the presence of the `Link` header of the HTTP response.
See: http://developer.skroutz.gr/api/v3/#pagination

When the header is missing, the client does not make assumptions and without pagination information, the following methods are designed to return:

* first_page? => true
* last_page? => true
* first => nil
* last => nil
* next =>nil
* previous => nil

Does this make things clear for you?

**Comment by GusAndrianos** [comment]
Yes that helps. Okay, so, in order to fix this, is there anything I can do before making the request? 

I am very new to the API, so, I am sorry for being noobish.
The biggest issue I have is not knowing how to transfer the documentation to Ruby code.

**Comment by GusAndrianos** [comment]
@Zorbash What should I look for in the logs? Can you suggest a way to make this work?

**Comment by Zorbash** [comment]
@GusAndrianos You should look for the `link` header. 

 In any case to keep this issue open, you need to provide a test case of the behaviour you expect from the client, or proceed with troubleshooting via email (mailto: api[at]skroutz.gr).
